// Auth
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGOUT = 'LOGOUT';
// Profile
export const PROFILE_EDIT_SUCCESS = 'PROFILE_EDIT_SUCCESS';
export const PROFILE_EDIT_FAIL = 'PROFILE_EDIT_FAIL';
export const PROFILE_EDIT_REQUEST = 'PROFILE_EDIT_REQUEST';
export const PASSWORD_EDIT_SUCCESS = 'PASSWORD_EDIT_SUCCESS';
export const PASSWORD_EDIT_FAIL = 'PASSWORD_EDIT_FAIL';
export const PASSWORD_EDIT_REQUEST = 'PASSWORD_EDIT_REQUEST';
export const DELETE_PROFILE_SUCCESS = 'DELETE_PROFILE_SUCCESS';
export const DELETE_PROFILE_FAIL = 'DELETE_PROFILE_FAIL';
export const DELETE_PROFILE_REQUEST = 'DELETE_PROFILE_REQUEST';
// Products
export const LOAD_PRODUCTS_REQUEST = 'LOAD_PRODUCTS_REQUEST';
export const LOAD_PRODUCTS = 'LOAD_PRODUCTS';
export const FAIL_LOADING = 'FAIL_LOADING';
export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST';
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS';
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL';
export const PRODUCT_DELETE_REQUEST = 'PRODUCT_DELETE_REQUEST';
export const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS';
export const PRODUCT_DELETE_FAIL = 'PRODUCT_DELETE_FAIL';
export const PRODUCT_EDIT_REQUEST = 'PRODUCT_EDIT_REQUEST';
export const PRODUCT_EDIT_SUCCESS = 'PRODUCT_EDIT_SUCCESS';
export const PRODUCT_EDIT_FAIL = 'PRODUCT_EDIT_FAIL';
export const REVIEW_SUBMIT_REQUEST = 'REVIEW_SUBMIT_REQUEST';
export const REVIEW_SUBMIT_SUCCESS = 'REVIEW_SUBMIT_SUCCESS';
export const REVIEW_SUBMIT_FAIL = 'REVIEW_SUBMIT_FAIL';
export const PRODUCTS_SEARCH_FAIL = 'PRODUCTS_SEARCH_FAIL';
export const PRODUCTS_SEARCH_REQUEST = 'PRODUCTS_SEARCH_REQUEST';
export const PRODUCTS_SEARCH_SUCCESS = 'PRODUCTS_SEARCH_SUCCESS';
// Cart

export const LOAD_CART = 'LOAD_CART';
export const FAIL_LOADING_CART = 'FAIL_LOADING_CART';
export const UPDATE_CART = 'UPDATE_CART';
export const UPDATE_CART_FAIL = 'UPDATE_CART_FAIL';
export const REMOVE_CART = 'REMOVE_CART';
export const REMOVE_CART_FAIL = 'REMOVE_CART_FAIL';
export const SAVE_SHIPPING_ADDRESS = 'SAVE_SHIPPING_ADDRESS';
export const SAVE_EMAIL = 'SAVE_EMAIL';
export const CLEAR_CART = 'CLEAR_CART';

// Orders
export const ORDER_SUBMIT_SUCCESS = 'ORDER_SUBMIT_SUCCESS';
export const ORDER_SUBMIT_FAIL = 'ORDER_SUBMIT_FAIL';
export const ORDER_SUBMIT_REQUEST = 'ORDER_SUBMIT_REQUEST';
export const ORDERS_LOADING_SUCCESS = 'ORDERS_LOADING_SUCCESS';
export const ORDERS_LOADING_FAIL = 'ORDERS_LOADING_FAIL';
export const ORDERS_LOADING_REQUEST = 'ORDERS_LOADING_REQUEST';
export const ORDER_LOADING_SUCCESS = 'ORDER_LOADING_SUCCESS';
export const ORDER_LOADING_FAIL = 'ORDER_LOADING_FAIL';
export const ORDER_LOADING_REQUEST = 'ORDER_LOADING_REQUEST';
export const ORDER_CLEAR = 'ORDER_CLEAR';
export const ORDER_CHARGE_REQUEST = 'ORDER_CHARGE_REQUEST';
export const ORDER_CHARGE_SUCCESS = 'ORDER_CHARGE_SUCCESS';
export const ORDER_CHARGE_FAIL = 'ORDER_CHARGE_FAIL';
export const ORDER_SEARCH_REQUEST = 'ORDER_SEARCH_REQUEST';
export const ORDER_SEARCH_SUCCESS = 'ORDER_SEARCH_SUCCESS';
export const ORDER_SEARCH_FAIL = 'ORDER_SEARCH_FAIL';
export const ORDER_DELIVERED_REQUEST = 'ORDER_DELIVERED_REQUEST';
export const ORDER_DELIVERED_SUCCESS = 'ORDER_DELIVERED_SUCCESS';
export const ORDER_DELIVERED_FAIL = 'ORDER_DELIVERED_FAIL';

// errors and success messages

export const CLEAR_ALL_ALERTS = 'CLEAR_ALL_ALERTS';
export const SET_ERROR_ALERT = 'SET_ERROR_ALERT';
export const SET_SUCCESS_ALERT = 'SET_SUCCESS_ALERT';
